name: Playit.gg (unofficial)
version: 0.9.3
slug: playit-gg
description: Playit.gg client add-on for Home Assistant
url: https://github.com/MegaTheLEGEND/Homeassistant-addons
maintainer: Your Name <your@email.com>
arch:
  - aarch64
  - amd64
options:
  log_level:
    name: Log Level
    description: Log level for the Playit.gg client add-on.
    default: info
    required: true
  save_directory:
    name: Save Directory
    description: Directory where Playit.gg client will save files.
    default: /path/to/save/directory
    required: true

schema:
  log_level: str
